- name: Deploy
  hosts: all
  gather_facts: yes

  tasks:
    - name: Log into GitHub Container Registry
      shell: "echo {{ registry_token }} | docker login ghcr.io -u {{ github_user }} --password-stdin"
      no_log: true 

    - name: Docker compose up
      shell: |
        export ASPNETCORE_ENVIRONMENT="Production"
        export ASPNETCORE_URLS="http://*:5006"
        export Jwt__SecretKey="{{ jwt_secret }}"
        
        # Używamy zmiennych z GitHuba, z bezpiecznym fallbackiem na 'root'
        export POSTGRES_DB="terminal"
        export POSTGRES_USER="{{ postgres_user | default('root') }}"
        export POSTGRES_PASSWORD="{{ postgres_pass | default('root') }}"
        
        export Postgres__ConnectionString="Host=database;Database=terminal;Username={{ postgres_user | default('root') }};Password={{ postgres_pass | default('root') }};Include Error Detail=true"
        
        export OTEL_ENDPOINT="{{ otel_endpoint }}"
        export OTEL_HEADERS="authorization={{ otel_headers }}"
        export OTEL_RESOURCE_ATTRIBUTES="{{ otel_attributes }}"
        
        export COMPOSE_INTERACTIVE_NO_CLI=1
        export COMPOSE_MENU=0
        
        docker compose -f {{ compose_image }} pull
        yes | docker compose --ansi never -f {{ compose_image }} up -d --remove-orphans
      args:
        executable: /bin/bash
      register: compose_up
      ignore_errors: yes

    - name: Show logs on failure
      shell: "docker logs terminal.server --tail 100"
      when: compose_up is failed or (compose_up.rc is defined and compose_up.rc != 0)
      register: server_logs

    - name: Final check
      fail:
        msg: "Deployment failed! App logs: {{ server_logs.stdout | default('No logs available') }}"
      when: compose_up is failed or (compose_up.rc is defined and compose_up.rc != 0)