name: Build docker images

on:
  workflow_run:
    workflows: ["Create release from tag"]
    types:
      - completed

  workflow_dispatch:

jobs:
  build-and-push-images:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/terminal-docker.yml
    with:
      registry-url: ghcr.io
      registry-username: ${{ github.actor }}
    secrets:
      registry-token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    needs: [build-and-push-images]
    uses: ./.github/workflows/terminal-ansible.yml
    secrets:
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      otel-endpoint: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
      otel-headers: "authorization=${{ secrets.HYPERDX_API_KEY }}"
      hdx-token: ${{ secrets.HYPERDX_API_KEY }}
      aspnetcore-urls: ${{ secrets.ASPNETCORE_URLS }}
      admin-email: ${{ secrets.ADMIN_EMAIL }}
      admin-password: ${{ secrets.ADMIN_PASSWORD }}
      ansible-user: ${{ secrets.ANSIBLE_USER }}
      deployment-targets: ${{ secrets.DEPLOYMENT_TARGETS }}
      registry-token: ${{ secrets.GITHUB_TOKEN }}
