name: Build docker images

on:
  workflow_run:
    workflows: ["Create release from tag"]
    types:
      - completed

  workflow_dispatch:

jobs:
  build-and-push-images:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/terminal-docker.yml
    with:
      registry-url: ghcr.io
      registry-username: ${{ github.actor }}
    secrets:
      registry-token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    needs: [build-and-push-images]
    uses: ./.github/workflows/terminal-ansible.yml
    secrets:
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      ansible-user: ${{ secrets.ANSIBLE_USER }}
      deployment-targets: ${{ secrets.DEPLOYMENT_TARGETS }}
