on:
  workflow_call:
    secrets:
      ssh-private-key:
        required: true
      ansible-user:
        required: true
      deployment-targets:
        required: true

jobs:
  deploy:
    name: Deploy Ansible Playbook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          echo "${{ secrets.ssh-private-key }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Create Ansible inventory
        id: make-inventory
        uses: ./.github/actions/make-inventory
        with:
          host-list: ${{ secrets.deployment-targets }}
          group-name: web

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible
          
      - name: Run Ansible Playbook
        env:
          ANSIBLE_USER: ${{ secrets.ansible-user }}
          ANSIBLE_HOST_KEY_CHECKING: false
          TMPDIR: "/home/${{ secrets.ansible-user }}/.ansible_tmp"
          TEMP: "/home/${{ secrets.ansible-user }}/.ansible_tmp"
          TMP: "/home/${{ secrets.ansible-user }}/.ansible_tmp"
          ANSIBLE_REMOTE_TMP: "/home/${{ secrets.ansible-user }}/.ansible_tmp"
          ANSIBLE_PIPELINING: "True"
          
        run: |
          ssh -o StrictHostKeyChecking=no -p 50022 -i private_key.pem ${{ secrets.ansible-user }}@153.19.51.139 "mkdir -p ~/.ansible_tmp && chmod 700 ~/.ansible_tmp"
          
          ansible-playbook -i inventory.ini ansible/deploy-playbook.yml \
            --extra-vars "compose_image=oci://ghcr.io/${{ github.repository_owner }}/terminal/compose:latest" \
            --extra-vars "registry_token=${{ secrets.GITHUB_TOKEN }}" \
            --extra-vars "github_user=${{ github.actor }}" \
            --private-key private_key.pem -u ${{ secrets.ansible-user }}
